-- Create favorites table for saved vehicles
CREATE TABLE IF NOT EXISTS public.favorites
(
    favorite_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_id integer NOT NULL,
    inv_id integer NOT NULL,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT favorites_pkey PRIMARY KEY (favorite_id),
    CONSTRAINT fk_account_favorites FOREIGN KEY (account_id) 
        REFERENCES public.account (account_id) ON DELETE CASCADE,
    CONSTRAINT fk_inventory_favorites FOREIGN KEY (inv_id) 
        REFERENCES public.inventory (inv_id) ON DELETE CASCADE,
    CONSTRAINT unique_account_favorite UNIQUE (account_id, inv_id)
);
